
dropWizardFactory: com.codeheadsystems.keystore.dagger.DynamoDBServer
logging:
  level: INFO
  loggers:
    com.codeheadsystems: DEBUG
    software.amazon: INFO
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

#metrics:
#  frequency: 1 minute
#  reportOnStop: true
#  reporters:
#    - type: log
#      logger: metrics
#      markerName: SLF4j
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: keystore
#      transport: tcp

dataStore:
  connectionUrl: http://localhost:8000
  username: someone
  password: secret

health:
  healthCheckUrlPaths: [ "/health-check" ]
  healthChecks:
    - name: deadlocks
      type: alive
      critical: true
      initialState: true
      schedule:
        checkInterval: 10s
        downtimeInterval: 2s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: BasicHealthCheck
      type: alive
      critical: true
      initialState: false
      schedule:
        checkInterval: 60s
        downtimeInterval: 2s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2