
logging:
  level: INFO
  loggers:
    com.codeheadsystems: DEBUG
    software.amazon: INFO
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"