services:
  cassandra:
    image: cassandra:4.0.5
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SNITCH=GossipingPropertyFileSnitch
      - JVM_OPTS=-Dcassandra.skip_wait_for_gossip_to_settle=0 -Dcassandra.initial_token=0
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
